title: Thư Viện Ma Trận
theme: just-the-docs
color_scheme: dark
markdown: kramdown

url: https://gamingwithevets.github.io

aux_links:
  "Xem repository trên GitHub": "//github.com/gamingwithevets/thu-vien-ma-tran"

footer_content: "(c) 2023 <a href=\"/\">gamingwithevets.github.io</a>"

last_edit_timestamp: true
last_edit_time_format: "%d/%m/%Y"

nav_sort: case_insensitive
