title: Thư Viện Ma Trận
theme: just-the-docs
color_scheme: dark

url: https://gamingwithevets.github.io
  
footer_content: "(c) 2023 <a href=\"/\">gamingwithevets.github.io</a>"

last_edit_timestamp: true
last_edit_time_format: "%d/%m/%Y"
    
search.rel_url: false
