title: Thư Viện Ma Trận
theme: just-the-docs
color_scheme: dark

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

url: https://gamingwithevets.github.io

logo: "/images/logo.png"
favicon_ico: "/images/favicon.png"

aux_links:
  "Xem repository trên GitHub": "//github.com/gamingwithevets/thu-vien-ma-tran"

footer_content: "(c) <a href=\"/\">gamingwithevets.github.io</a>"

nav_sort: case_insensitive

last_edit_time_format: "%d/%m/%Y %H:%M:%S (UTC%z)"
timezone: Asia/Bangkok

plugins:
  - jekyll-last-modified-at
