title: Thư Viện Ma Trận
theme: just-the-docs
color_scheme: dark

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

url: https://gamingwithevets.github.io

logo: "/images/logo.png"
favicon_ico: "/images/favicon.png"

aux_links:
  "Xem repository trên GitHub": "//github.com/gamingwithevets/thu-vien-ma-tran"

footer_content: "(c) <a href=\"/\">gamingwithevets.github.io</a>"

gh_edit_link: true
gh_edit_link_text: "Xem bản gốc/chỉnh sửa trang này trên GitHub"
gh_edit_repository: "https://github.com/gamingwithevets/thu-vien-ma-tran"
gh_edit_branch: "main"
gh_edit_view_mode: "blob"

nav_sort: case_insensitive

last_edit_time_format: "%d/%m/%Y %H:%M:%S (UTC%z)"
timezone: Asia/Bangkok

nav_external_links:
  - title: [English] Casio Calculator Hacking on Discord
    url: http://discord.gg/QjGpH6rSQQ
  - title: Thư Viện Ma Trận trên Zalo
    url: https://zalo.me/g/bgljzf836

plugins:
  - jekyll-last-modified-at
